### ISSUE TITLE
Generate multiple reports and aggregate them

### ISSUE THREAD

**Issue by brodock** [ArturT/knapsack#15]
I would like to start coding and contribute to the project the mentioned feature.
Take this scenarios as example:

Having 5 parallel CI containers running the same commit at first time, I would expect that every container generates execution for the files they are executing, and store in a specific folder, that will be aggregated at the end of the proccess.

At the next execution, instead of loading a single report file, it will load every file it can locates on that folder, and aggregate all values, so even the first run will be fast enough.

**Comment by ArturT** [comment]
You assume you will keep cached reports on CI without committing them into repository?

Would you like to add to the report's file name the commit hash (and maybe branch name and CI node index) so you can identify which report you can use next time. Or just use proper directory structure.


`"... that will be aggregated at the end of the proccess."`
Your CI servers have common cache space where you will do aggregation? How can you know when it should happen, when the last CI executed tests and we are ready to start aggregate?


There is also question which files should be run on which CI server when you run tests for the first time and you don't have report yet. For this problem we can already use knapsack and assume that report is blank (empty json `{}`) so knapsack will split different tests on different CI nodes.

`"At the next execution, instead of loading a single report file, it will load every file it can locates on that folder, and aggregate all values, so even the first run will be fast enough."`
We can aggregate reports files with the same hash commit or the last hash commit created for the branch you are trying to tests (in case when someone push new code and we don't have report for it yet. Then we can use the latest data we know about the branch). In that case we don't need to aggregate reports at the end, we can do it just before run tests. And we have assumption that we have shared folder with cached old reports across CI servers.


In case we will need commit hash or branch name we should be able to set `cvs` config to `:git` and allow to add new adapters to gem so people can use it with other tool than git. 
Would be good to allow to use knapsack as it is know. We can add just a new way of using it, you've described. And last thing I guess I need to simplify or split read me because it will be to big when we will have to ways.

Thanks for idea.

**Comment by ArturT** [comment]
Here is similar problem and solution https://github.com/ArturT/knapsack/issues/34
