### ISSUE TITLE
Incremental report generation

### ISSUE THREAD

**Issue by ghempton** [ArturT/knapsack#23]
As our test suite becomes increasingly large and increasingly parallel, generating a full knapsack report becomes increasingly time-consuming and difficult.

It would be great to be able to run a subset of the tests and to only update their entries in the knapsack report without clearing the rest.

**Comment by ArturT** [comment]
For now as a temporary solution you can generate partial reports this way

```
KNAPSACK_GENERATE_REPORT=true bundle exec rspec spec/models
KNAPSACK_GENERATE_REPORT=true bundle exec rspec spec/controllers
KNAPSACK_GENERATE_REPORT=true bundle exec rspec spec/other_dir
```

You can add generated file paths to report. In case when report will contain paths that no more exists then knapsack can handle that and ignore those test files.


Currently I'm working on Knapsack Pro http://knapsack.launchrock.com/
Right now I'm doing some early testing on my own projects and in a few weeks I will start testing with early adopters. If you want to try then please send me email https://github.com/ArturT/knapsack/blob/master/knapsack.gemspec#L10 so I will contact you. Please send me how many test suites you have. Just rspec one test suite? Or maybe rspec and cucumber. I will need to generate api key for each of you test suite. 

Would be cool to try knapsack pro on large project. Please send my info how many nodes you have and how long your tests are right now. Thanks!

**Comment by Drowze** [comment]
We've been facing this in our project (where we use the knapsack gem, but not yet knapsack pro). Since we have a lot of tests, inevitably we also have some flaky tests.

When trying to generate our full knapsack report, we often stumble on some flaky test and have to restart the whole workflow - which is pretty slow and ends up being pretty time inneficient.
What we plan on doing (but haven't got to it yet) is to generate a new knapsack report running only a subset of the tests (determined by the currently existing knapsack report). We'd get the subsets of the report generated in a GitHub Actions matrix, then have a later step on the CI to merge the JSONs into a single knapsack report.

In case someone is interested in a similar situation, I believe the following snippet should do the trick:
```bash
CI_NODE_TOTAL=16 CI_NODE_INDEX=0 ruby -rknapsack -e '
  Knapsack::Report.instance.config(report_path: Knapsack::Adapters::RSpecAdapter::REPORT_PATH)
  allocator = Knapsack::Allocator.new(
    ci_node_total: Integer(ENV.fetch("CI_NODE_TOTAL")),
    ci_node_index: Integer(ENV.fetch("CI_NODE_INDEX")),
    test_file_pattern: Knapsack::Adapters::RSpecAdapter::TEST_DIR_PATTERN,
    report: Knapsack::Report.instance.open
  )
  puts allocator.stringify_node_tests' | xargs KNAPSACK_GENERATE_REPORT=true bundle exec rspec
```

**Comment by ArturT** [comment]
@Drowze Thanks for sharing the example.

Flaky tests can be a pain. We found out that tracking tests over a longer period of time also helps reduce unbalanced builds with flaky tests. We did several improvements on the Knapsack Pro API side in recent months related to that. 

Just last week, we released a new, more generous free plan if you would like to give it a try.
https://knapsackpro.com

There are also a migration steps here:
https://github.com/KnapsackPro/knapsack/blob/master/MIGRATE_TO_KNAPSACK_PRO.md

I hope this helps.
