### ISSUE TITLE
Push Timecop to development dependencies

### ISSUE THREAD

**Issue by madejejej** [ArturT/knapsack#55]
In the gemspec the Timecop gem is listed as a regular dependency:

```ruby
  spec.add_dependency 'timecop', '>= 0.1.0'
```

You probably want to include it only as a development dependency since it's only being used in `spec/knapsack/tracker_spec.rb`: 

https://github.com/ArturT/knapsack/search?utf8=%E2%9C%93&q=Timecop&type=

**Comment by ArturT** [comment]
It is used here:
https://github.com/ArturT/knapsack/blob/master/lib/knapsack/tracker.rb#L84

```ruby
def now_without_mock_time
  Time.now_without_mock_time
end
```

`now_without_mock_time` is Timecop method: https://github.com/travisjeffery/timecop/search?utf8=%E2%9C%93&q=now_without_mock_time&type=

Anyway thanks for checking :)

**Comment by ArturT** [comment]
Note to myself. It was done this way on purpose. Timecop is a regular dependency and I don't want to use `Time.now` because someone could stub `Time.now` and that would prevent to determine the correct time.

Here is related commit in knapsack_pro https://github.com/KnapsackPro/knapsack_pro-ruby/commit/f6fe6a2af1be289f23ad0337f1081d032bfa109c/knapsack_pro.gemspec#diff-0

**Comment by ArturT** [comment]
I figured out how `Timecop` could be moved to development dependencies. I did change in `knapsack_pro` https://github.com/KnapsackPro/knapsack_pro-ruby/pull/38
A similar thing could be done here in `knapsack` gem. If anyone wants to help it's basically copy & paste from the [PR](https://github.com/KnapsackPro/knapsack_pro-ruby/pull/38)
